### ISSUE TITLE
Choose Domain

### ISSUE THREAD

**Issue by scottgarner** [objectnormal/maevr#1]
What domain are we going to use? maevr.com? davidlobser.cool?

We'd have maevr.com redirect to www.maevr.com for the CDN stuff to work. For the event, live.maevr.com would redirect to www.maevr.com/#live and ws.maevr.com would be the Heroku server, though nobody need ever see that.

Let me know so I can get started.

**Comment by dlobser** [comment]
asking

**Comment by scottgarner** [comment]
maevr.vertigomusic.com
