### ISSUE TITLE
Disable lens distortion correction. 

### ISSUE THREAD

**Issue by scottgarner** [objectnormal/maevr#14]

**Comment by scottgarner** [comment]
Looks like things changed in the polyfill in the new version. I filed an issue with the author.

**Comment by dlobser** [comment]
Can we revert to an old version if we can sort this? It really kills performance

**Comment by scottgarner** [comment]
I don't want to revert because so many things are cleaned up.

I have a bug filed with the developer. I'll try to figure something out
tonight.

-S

**Comment by scottgarner** [comment]
I added a hack for this until it's really figured out.

**Comment by scottgarner** [comment]
Should be covered with `isUndistorted: true`. I need to comment on the issue in the polyfill repository.

**Comment by scottgarner** [comment]
Reverted to the old manager and polyfill. We should be okay.
