### ISSUE TITLE
Have a quick look at camera animation

### ISSUE THREAD

**Issue by dlobser** [objectnormal/maevr#6]
I think it'll make sense to just roll my own tween - i probably should have just done it before - i even added a smoothstep function for just that reason. If you'd like to look at what's there here are some notes about that:

in maevr.js init() 

MAEVR.parentCamera = CamUtil.setParentCam( MAEVR.camera, {
      startPosition: new THREE.Vector3(0,12,0),
      cameraSpeed: 1,
      camKeyTimes:[1000, 2736, 5840, 6591, 6628, 6979, 7766]
    });

and in maevr.gui.staticbegin()

 setTimeout(function(){
      CamUtil.startCameraAnimationSeries( MAEVR.parentCamera );
    },50);  

TWEEN.update() is in maevr.experience

otherwise all cam logic is in cameraUtil.js

**Comment by scottgarner** [comment]
We're good on this, right? Closing?
