### ISSUE TITLE
Stem Selections

### ISSUE THREAD

**Issue by scottgarner** [objectnormal/maevr#8]
Make your stem choices. Either individual stems or stems I can bundle into subtracts.

**Comment by dlobser** [comment]
eGTR1-Mae VR.wav
HookMel-Mae VR.wav

**Comment by scottgarner** [comment]
Do you also want to keep a full-track version or just those two stems?

**Comment by scottgarner** [comment]
So I generated and pushed these stems, but the stem tracks don't line up with the mp3 we got.

In other words, my data matches the stems, but the stems don't match the audio, meaning the data seems off.

**Comment by scottgarner** [comment]
I'll recheck when we get new audio files.

**Comment by scottgarner** [comment]
Never mind, it seemed to just be a one-second offset. Let me know.

`MAEVR.Stems.getStemValue(0)` should give you `eGTR1-Mae VR.wav`
`MAEVR.Stems.getStemValue(1)` should give you `HookMel-Mae VR.wav`

Let me know if it seems crazy. I'm not sure my approach was the best.
